### ISSUE TITLE
Not an Issue. Only a little question.

### ISSUE THREAD

**Issue by santiblanko** [fransyozef/cryptofyer#58]
I want a program like coinexchange.io
Can you work in it?

**Comment by fransyozef** [comment]
What do you mean a program? Like the whole site? Or just the API?

**Comment by santiblanko** [comment]
Full site. I need sell this type of systems. Are very demanded.

**Comment by fransyozef** [comment]
No, this is only to connect your own software to an exhange (just like coinexchange)
